
/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */

#if defined(HAVE_PRAGMA_ONCE)
#pragma once
#endif

#ifndef MAPICON_RECORD_H__
#define MAPICON_RECORD_H__

class MapIconRecord;

#include "CTPDatabase.h"
#include "CTPRecord.h"
class CivArchive;

#define k_Num_MapIconRecord_Tokens 2


class MapIconRecord : public CTPRecord
{
public:
    typedef sint32 (MapIconRecord::*IntAccessor)() const;
    typedef bool   (MapIconRecord::*BoolAccessor)() const;
    typedef double (MapIconRecord::*FloatAccessor)() const ;
    typedef bool   (MapIconRecord::*BitIntAccessor)(sint32 &val) const;
    typedef bool   (MapIconRecord::*BitFloatAccessor)(double &val) const;
    typedef sint32 (MapIconRecord::*IntArrayAccessor)(sint32 index) const;
    typedef double (MapIconRecord::*FloatArrayAccessor)(sint32 index) const;

private:
    char *            m_Value;
    char *            m_NameText;
    bool m_hasGovernmentsModified; // GovMod specific flag

public:
    MapIconRecord() { Init(); };
    MapIconRecord(CivArchive &archive) { Serialize(archive); };
    MapIconRecord(MapIconRecord const & rval) { Init(); *this = rval; }
    ~MapIconRecord();
    MapIconRecord const & operator = (MapIconRecord const & rval);

    void Init();
    void Serialize(CivArchive &archive);

    void CheckRequiredFields(DBLexer *lex);
    sint32 Parse(DBLexer *lex, sint32 numRecords);

    void ResolveDBReferences();
    void Merge(const MapIconRecord & rval);

    char const * GetValue() const { return m_Value; }
    char const * GetNameText() const { return m_NameText; }
    bool GetHasGovernmentsModified() const { return m_hasGovernmentsModified; }
    sint32 GenericGetNumGovernmentsModified() const { return 0; }
    sint32 GenericGetGovernmentsModifiedIndex(sint32 index) const { return -1; }

}; /* MapIconRecord */

struct MapIconRecordAccessorInfo
{
    MapIconRecord::IntAccessor        m_intAccessor;
    MapIconRecord::BoolAccessor       m_boolAccessor;
    MapIconRecord::FloatAccessor      m_floatAccessor;
    MapIconRecord::BitIntAccessor     m_bitIntAccessor;
    MapIconRecord::BitFloatAccessor   m_bitFloatAccessor;
    MapIconRecord::IntArrayAccessor   m_intArrayAccessor;
    MapIconRecord::FloatArrayAccessor m_floatArrayAccessor;
};

extern MapIconRecordAccessorInfo      g_MapIconRecord_Accessors[];
extern CTPDatabase<MapIconRecord> *   g_theMapIconDB;

extern const char * g_MapIcon_Tokens[];

#endif
