
/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */

#if defined(HAVE_PRAGMA_ONCE)
#pragma once
#endif

#ifndef WONDER_RECORD_H__
#define WONDER_RECORD_H__

class WonderRecord;

#include "CTPDatabase.h"
#include "CTPRecord.h"
class CivArchive;
class AdvanceRecord;
class BuildingRecord;
class CityStyleRecord;
class CivilisationRecord;
class FeatRecord;
class GovernmentRecord;
class IconRecord;
class MapIconRecord;
class ResourceRecord;
class TerrainImprovementRecord;
class WonderMovieRecord;
class BuildingRecord;
class BuildingRecord;

#define k_Num_WonderRecord_Tokens 147

//
// m_flags0: Wonder
#define k_Wonder_ShowCityIconTop_Bit             0x00000001
#define k_Wonder_ShowCityIconBottom_Bit          0x00000002
#define k_Wonder_SquaredBorderRadius_Bit         0x00000004
#define k_Wonder_IntBorderRadius_Bit             0x00000008
#define k_Wonder_OnePerCiv_Bit                   0x00000010
#define k_Wonder_IsReligionIcon_Bit              0x00000020
#define k_Wonder_IsHolyCity_Bit                  0x00000040
#define k_Wonder_ReduceReadinessCost_Bit         0x00000080
#define k_Wonder_EmbassiesEverywhere_Bit         0x00000100
#define k_Wonder_DecCrimePercent_Bit             0x00000200
#define k_Wonder_IncKnowledgePercent_Bit         0x00000400
#define k_Wonder_DecEmpireSize_Bit               0x00000800
#define k_Wonder_IncHappinessEmpire_Bit          0x00001000
#define k_Wonder_CloseEmbassies_Bit              0x00002000
#define k_Wonder_ReformCities_Bit                0x00004000
#define k_Wonder_FreeSlaves_Bit                  0x00008000
#define k_Wonder_ProhibitSlavers_Bit             0x00010000
#define k_Wonder_IncConvertedCitiesFeePercent_Bit 0x00020000
#define k_Wonder_GoldPerWaterTradeRoute_Bit      0x00040000
#define k_Wonder_GoldPerTelevision_Bit           0x00080000
#define k_Wonder_GlobalRadar_Bit                 0x00100000
#define k_Wonder_SpiesEverywhere_Bit             0x00200000
#define k_Wonder_GoldPerInternationalTradeRoute_Bit 0x00400000
#define k_Wonder_ProtectFromBiologicalWarfare_Bit 0x00800000
#define k_Wonder_PollutersToParks_Bit            0x01000000
#define k_Wonder_EnableParkRangers_Bit           0x02000000
#define k_Wonder_ReduceWorldPollution_Bit        0x04000000
#define k_Wonder_AllCitizensContent_Bit          0x08000000
#define k_Wonder_EliminateNukes_Bit              0x10000000
#define k_Wonder_AllBoatsDeepWater_Bit           0x20000000
#define k_Wonder_IncreaseBoatMovement_Bit        0x40000000
#define k_Wonder_FreeTradeRoutes_Bit             0x80000000
//
// m_flags1: Wonder
#define k_Wonder_DecreaseMaintenance_Bit         0x00000001
#define k_Wonder_RandomAdvanceChance_Bit         0x00000002
#define k_Wonder_IncreaseHp_Bit                  0x00000004
#define k_Wonder_MultiplyTradeRoutes_Bit         0x00000008
#define k_Wonder_ForcefieldEverywhere_Bit        0x00000010
#define k_Wonder_IncreaseScientists_Bit          0x00000020
#define k_Wonder_OtherCivRandomAdvanceChance_Bit 0x00000040
#define k_Wonder_IncreaseProduction_Bit          0x00000080
#define k_Wonder_BonusGold_Bit                   0x00000100
#define k_Wonder_CantBuildInSea_Bit              0x00000200
#define k_Wonder_CantBuildOnLand_Bit             0x00000400
#define k_Wonder_CoastalBuilding_Bit             0x00000800
#define k_Wonder_EnablesPunativeAirstrikes_Bit   0x00001000
#define k_Wonder_IncreaseFoodAllCities_Bit       0x00002000
#define k_Wonder_TemporaryFullHappiness_Bit      0x00004000
#define k_Wonder_RevoltingCitiesJoinPlayer_Bit   0x00008000
#define k_Wonder_NoPollutionUnhappiness_Bit      0x00010000
#define k_Wonder_EmbassiesEverywhereEvenAtWar_Bit 0x00020000
#define k_Wonder_IncreaseSpecialists_Bit         0x00040000
#define k_Wonder_IncreaseCathedrals_Bit          0x00080000
#define k_Wonder_IncreaseBrokerages_Bit          0x00100000
#define k_Wonder_IncreaseRegard_Bit              0x00200000
#define k_Wonder_PreventConversion_Bit           0x00400000
#define k_Wonder_ProtectFromBarbarians_Bit       0x00800000
#define k_Wonder_StartGaiaController_Bit         0x01000000
#define k_Wonder_GLHidden_Bit                    0x02000000
#define k_Wonder_BuildingFeat_Bit                0x04000000
#define k_Wonder_BuildingGold_Bit                0x08000000
#define k_Wonder_BuildingEverywhere_Bit          0x10000000
#define k_Wonder_ActualBuildingEverywhere_Bit    0x20000000
#define k_Wonder_BuildingEffectEverywhere_Bit    0x40000000
#define k_Wonder_ConflictsWithBuilding_Bit       0x80000000
//
// m_flags2: Wonder
#define k_Wonder_GoldPerBuildingAnywhere_Bit     0x00000001
#define k_Wonder_PollutionPercent_Bit            0x00000002
#define k_Wonder_PollutionAmount_Bit             0x00000004
#define k_Wonder_EnergyHunger_Bit                0x00000008
#define k_Wonder_ProducesEnergy_Bit              0x00000010
#define k_Wonder_EnergyHungerPerPop_Bit          0x00000020
#define k_Wonder_ProducesEnergyPerPop_Bit        0x00000040
#define k_Wonder_TooManyCitiesThresholdModifier_Bit 0x00000080
#define k_Wonder_TooManyCitiesCoefficientModifier_Bit 0x00000100
#define k_Wonder_RiotLevelModifier_Bit           0x00000200
#define k_Wonder_OtherPlayerRiotLevelModifier_Bit 0x00000400
//
// m_flags0: BuildingFeat
#define k_BuildingFeat_Num_Bit                   0x00000001
#define k_BuildingFeat_PercentCities_Bit         0x00000002
//
// m_flags0: BuildingGold
#define k_BuildingGold_Gold_Bit                  0x00000001
#define k_MAX_ObsoleteAdvance                5

class WonderRecord : public CTPRecord
{
public:
    typedef sint32 (WonderRecord::*IntAccessor)() const;
    typedef bool   (WonderRecord::*BoolAccessor)() const;
    typedef double (WonderRecord::*FloatAccessor)() const ;
    typedef bool   (WonderRecord::*BitIntAccessor)(sint32 &val) const;
    typedef bool   (WonderRecord::*BitFloatAccessor)(double &val) const;
    typedef sint32 (WonderRecord::*IntArrayAccessor)(sint32 index) const;
    typedef double (WonderRecord::*FloatArrayAccessor)(sint32 index) const;

    class BuildingFeat {
    private:
        uint32            m_flags0;
        sint32            m_Building; // Index into Building database
        sint32            m_NumValue;
        sint32            m_PercentCitiesValue;

    public:
        BuildingFeat();
        BuildingFeat(CivArchive & archive){ Serialize(archive); };
        ~BuildingFeat();
        BuildingFeat const & operator = (BuildingFeat const & rval);
        bool operator == (BuildingFeat const & rval) {
          if (m_Building != rval.m_Building)
             return false;
          return true;
        }

        void Serialize(CivArchive &archive);
        sint32 Parse(DBLexer *lex);
        static sint32 ParseInArray(DBLexer *lex, BuildingFeat **array, sint32 *numElements);
        static sint32 ParseInArray(DBLexer *lex, BuildingFeat *array, sint32 *numElements, sint32 maxSize);
        void ResolveDBReferences();

        sint32           GetBuildingIndex() const { return m_Building; }
        BuildingRecord const * GetBuilding() const;
        bool HasNum() const { return (m_flags0 & k_BuildingFeat_Num_Bit) != 0; }
        bool GetNum(sint32 & value) const
        {
            if (m_flags0 & k_BuildingFeat_Num_Bit)
            {
                value = m_NumValue;
            }
            return (m_flags0 & k_BuildingFeat_Num_Bit) != 0;
        }
        bool HasPercentCities() const { return (m_flags0 & k_BuildingFeat_PercentCities_Bit) != 0; }
        bool GetPercentCities(sint32 & value) const
        {
            if (m_flags0 & k_BuildingFeat_PercentCities_Bit)
            {
                value = m_PercentCitiesValue;
            }
            return (m_flags0 & k_BuildingFeat_PercentCities_Bit) != 0;
        }

    }; /* class BuildingFeat */

    class BuildingGold {
    private:
        uint32            m_flags0;
        sint32            m_Building; // Index into Building database
        sint32            m_GoldValue;

    public:
        BuildingGold();
        BuildingGold(CivArchive & archive){ Serialize(archive); };
        ~BuildingGold();
        BuildingGold const & operator = (BuildingGold const & rval);
        bool operator == (BuildingGold const & rval) {
          if (m_Building != rval.m_Building)
             return false;
          return true;
        }

        void Serialize(CivArchive &archive);
        sint32 Parse(DBLexer *lex);
        static sint32 ParseInArray(DBLexer *lex, BuildingGold **array, sint32 *numElements);
        static sint32 ParseInArray(DBLexer *lex, BuildingGold *array, sint32 *numElements, sint32 maxSize);
        void ResolveDBReferences();

        sint32           GetBuildingIndex() const { return m_Building; }
        BuildingRecord const * GetBuilding() const;
        bool HasGold() const { return (m_flags0 & k_BuildingGold_Gold_Bit) != 0; }
        bool GetGold(sint32 & value) const
        {
            if (m_flags0 & k_BuildingGold_Gold_Bit)
            {
                value = m_GoldValue;
            }
            return (m_flags0 & k_BuildingGold_Gold_Bit) != 0;
        }

    }; /* class BuildingGold */

private:
    uint32 m_flags0;
    uint32 m_flags1;
    uint32 m_flags2;
    sint32            m_ProductionCost;
    sint32            m_DefaultIcon; // Index into Icon database
    sint32            m_Movie; // Index into WonderMovie database
    sint32            m_Description;
    sint32            m_EnableAdvance; // Index into Advance database
    sint32            m_ObsoleteAdvance[k_MAX_ObsoleteAdvance]; // Index into Advance database
    sint32            m_numObsoleteAdvance;
    sint32          * m_PrerequisiteBuilding; // Index into Building database
    sint32            m_numPrerequisiteBuilding;
    sint32          * m_GovernmentsModified; // Index into Government database
    sint32            m_numGovernmentsModified;
    sint32          * m_CultureOnly; // Index into CityStyle database
    sint32            m_numCultureOnly;
    sint32          * m_GovernmentType; // Index into Government database
    sint32            m_numGovernmentType;
    sint32          * m_ObsoleteGovernmentType; // Index into Government database
    sint32            m_numObsoleteGovernmentType;
    sint32          * m_CityStyleOnly; // Index into CityStyle database
    sint32            m_numCityStyleOnly;
    sint32          * m_NeedsCityGood; // Index into Resource database
    sint32            m_numNeedsCityGood;
    sint32          * m_NeedsCityGoodAll; // Index into Resource database
    sint32            m_numNeedsCityGoodAll;
    sint32          * m_NeedsCityGoodAnyCity; // Index into Resource database
    sint32            m_numNeedsCityGoodAnyCity;
    sint32          * m_EnablesGood; // Index into Resource database
    sint32            m_numEnablesGood;
    sint32          * m_ShowOnMap; // Index into TerrainImprovement database
    sint32            m_numShowOnMap;
    sint32          * m_ShowOnMapRadius; // Index into TerrainImprovement database
    sint32            m_numShowOnMapRadius;
    sint32          * m_CivilisationOnly; // Index into Civilisation database
    sint32            m_numCivilisationOnly;
    sint32          * m_NeedsFeatToBuild; // Index into Feat database
    sint32            m_numNeedsFeatToBuild;
    sint32          * m_NeedsAnyPlayerFeatToBuild; // Index into Feat database
    sint32            m_numNeedsAnyPlayerFeatToBuild;
    sint32            m_ShowCityIconTopValue; // Index into MapIcon database
    sint32            m_ShowCityIconBottomValue; // Index into MapIcon database
    sint32            m_SquaredBorderRadiusValue;
    sint32            m_IntBorderRadiusValue;
    sint32            m_IsReligionIconValue; // Index into MapIcon database
    sint32            m_ReduceReadinessCostValue;
    sint32            m_DecCrimePercentValue;
    sint32            m_IncKnowledgePercentValue;
    sint32            m_DecEmpireSizeValue;
    sint32            m_IncHappinessEmpireValue;
    sint32            m_IncConvertedCitiesFeePercentValue;
    sint32            m_GoldPerWaterTradeRouteValue;
    sint32            m_GoldPerTelevisionValue;
    sint32            m_GoldPerInternationalTradeRouteValue;
    sint32            m_PollutersToParksValue;
    sint32            m_ReduceWorldPollutionValue;
    sint32            m_IncreaseBoatMovementValue;
    sint32            m_DecreaseMaintenanceValue;
    sint32            m_RandomAdvanceChanceValue;
    sint32            m_IncreaseHpValue;
    sint32            m_MultiplyTradeRoutesValue;
    sint32            m_IncreaseScientistsValue;
    sint32            m_OtherCivRandomAdvanceChanceValue;
    sint32            m_IncreaseProductionValue;
    sint32            m_BonusGoldValue;
    sint32            m_IncreaseFoodAllCitiesValue;
    sint32            m_TemporaryFullHappinessValue;
    sint32            m_IncreaseSpecialistsValue;
    sint32            m_IncreaseCathedralsValue;
    sint32            m_IncreaseBrokeragesValue;
    sint32            m_IncreaseRegardValue;
    BuildingFeat      m_BuildingFeatValue;
    BuildingGold      m_BuildingGoldValue;
    sint32            m_BuildingEverywhereValue; // Index into Building database
    sint32            m_ActualBuildingEverywhereValue; // Index into Building database
    sint32            m_BuildingEffectEverywhereValue; // Index into Building database
    sint32            m_ConflictsWithBuildingValue; // Index into Building database
    sint32          * m_BuildingAnywhere; // Index into Building database
    sint32            m_numBuildingAnywhere;
    sint32            m_GoldPerBuildingAnywhereValue;
    double            m_PollutionPercentValue;
    double            m_PollutionAmountValue;
    sint32          * m_ExcludedByBuilding; // Index into Building database
    sint32            m_numExcludedByBuilding;
    sint32          * m_ExcludedByWonder; // Index into Wonder database
    sint32            m_numExcludedByWonder;
    sint32            m_EnergyHungerValue;
    sint32            m_ProducesEnergyValue;
    sint32            m_EnergyHungerPerPopValue;
    sint32            m_ProducesEnergyPerPopValue;
    sint32            m_TooManyCitiesThresholdModifierValue;
    double            m_TooManyCitiesCoefficientModifierValue;
    sint32            m_RiotLevelModifierValue;
    sint32            m_OtherPlayerRiotLevelModifierValue;
    bool m_hasGovernmentsModified; // GovMod specific flag

public:
    WonderRecord() { Init(); };
    WonderRecord(CivArchive &archive) { Serialize(archive); };
    WonderRecord(WonderRecord const & rval) { Init(); *this = rval; }
    ~WonderRecord();
    WonderRecord const & operator = (WonderRecord const & rval);

    void Init();
    void Serialize(CivArchive &archive);

    void CheckRequiredFields(DBLexer *lex);
    sint32 Parse(DBLexer *lex, sint32 numRecords);

    void ResolveDBReferences();
    void Merge(const WonderRecord & rval);

    sint32 GetProductionCost() const { return m_ProductionCost; }
    sint32           GetDefaultIconIndex() const { return m_DefaultIcon; }
    IconRecord const * GetDefaultIcon() const;
    sint32           GetMovieIndex() const { return m_Movie; }
    WonderMovieRecord const * GetMovie() const;
    sint32 GetDescription() const { return m_Description; }
    sint32           GetEnableAdvanceIndex() const { return m_EnableAdvance; }
    AdvanceRecord const * GetEnableAdvance() const;
    sint32 GetObsoleteAdvanceIndex(sint32 index) const;
    const AdvanceRecord * GetObsoleteAdvance(sint32 index) const;
    sint32 GetNumObsoleteAdvance() const { return m_numObsoleteAdvance;}
    sint32 GetPrerequisiteBuildingIndex(sint32 index) const;
    const BuildingRecord * GetPrerequisiteBuilding(sint32 index) const;
    sint32 GetNumPrerequisiteBuilding() const { return m_numPrerequisiteBuilding;}
    sint32 GetGovernmentsModifiedIndex(sint32 index) const;
    const GovernmentRecord * GetGovernmentsModified(sint32 index) const;
    sint32 GetNumGovernmentsModified() const { return m_numGovernmentsModified;}
    sint32 GetCultureOnlyIndex(sint32 index) const;
    const CityStyleRecord * GetCultureOnly(sint32 index) const;
    sint32 GetNumCultureOnly() const { return m_numCultureOnly;}
    sint32 GetGovernmentTypeIndex(sint32 index) const;
    const GovernmentRecord * GetGovernmentType(sint32 index) const;
    sint32 GetNumGovernmentType() const { return m_numGovernmentType;}
    sint32 GetObsoleteGovernmentTypeIndex(sint32 index) const;
    const GovernmentRecord * GetObsoleteGovernmentType(sint32 index) const;
    sint32 GetNumObsoleteGovernmentType() const { return m_numObsoleteGovernmentType;}
    sint32 GetCityStyleOnlyIndex(sint32 index) const;
    const CityStyleRecord * GetCityStyleOnly(sint32 index) const;
    sint32 GetNumCityStyleOnly() const { return m_numCityStyleOnly;}
    sint32 GetNeedsCityGoodIndex(sint32 index) const;
    const ResourceRecord * GetNeedsCityGood(sint32 index) const;
    sint32 GetNumNeedsCityGood() const { return m_numNeedsCityGood;}
    sint32 GetNeedsCityGoodAllIndex(sint32 index) const;
    const ResourceRecord * GetNeedsCityGoodAll(sint32 index) const;
    sint32 GetNumNeedsCityGoodAll() const { return m_numNeedsCityGoodAll;}
    sint32 GetNeedsCityGoodAnyCityIndex(sint32 index) const;
    const ResourceRecord * GetNeedsCityGoodAnyCity(sint32 index) const;
    sint32 GetNumNeedsCityGoodAnyCity() const { return m_numNeedsCityGoodAnyCity;}
    sint32 GetEnablesGoodIndex(sint32 index) const;
    const ResourceRecord * GetEnablesGood(sint32 index) const;
    sint32 GetNumEnablesGood() const { return m_numEnablesGood;}
    sint32 GetShowOnMapIndex(sint32 index) const;
    const TerrainImprovementRecord * GetShowOnMap(sint32 index) const;
    sint32 GetNumShowOnMap() const { return m_numShowOnMap;}
    sint32 GetShowOnMapRadiusIndex(sint32 index) const;
    const TerrainImprovementRecord * GetShowOnMapRadius(sint32 index) const;
    sint32 GetNumShowOnMapRadius() const { return m_numShowOnMapRadius;}
    sint32 GetCivilisationOnlyIndex(sint32 index) const;
    const CivilisationRecord * GetCivilisationOnly(sint32 index) const;
    sint32 GetNumCivilisationOnly() const { return m_numCivilisationOnly;}
    sint32 GetNeedsFeatToBuildIndex(sint32 index) const;
    const FeatRecord * GetNeedsFeatToBuild(sint32 index) const;
    sint32 GetNumNeedsFeatToBuild() const { return m_numNeedsFeatToBuild;}
    sint32 GetNeedsAnyPlayerFeatToBuildIndex(sint32 index) const;
    const FeatRecord * GetNeedsAnyPlayerFeatToBuild(sint32 index) const;
    sint32 GetNumNeedsAnyPlayerFeatToBuild() const { return m_numNeedsAnyPlayerFeatToBuild;}
    bool HasShowCityIconTop() const { return (m_flags0 & k_Wonder_ShowCityIconTop_Bit) != 0; }
    bool GetShowCityIconTopIndex(sint32 & index) const
    {
        index = (m_flags0 & k_Wonder_ShowCityIconTop_Bit) ? m_ShowCityIconTopValue : -1;
        return (m_flags0 & k_Wonder_ShowCityIconTop_Bit) != 0;
    }
    bool GetShowCityIconTop(const MapIconRecord * & rec) const;
    const MapIconRecord * GetShowCityIconTopPtr() const;
    bool HasShowCityIconBottom() const { return (m_flags0 & k_Wonder_ShowCityIconBottom_Bit) != 0; }
    bool GetShowCityIconBottomIndex(sint32 & index) const
    {
        index = (m_flags0 & k_Wonder_ShowCityIconBottom_Bit) ? m_ShowCityIconBottomValue : -1;
        return (m_flags0 & k_Wonder_ShowCityIconBottom_Bit) != 0;
    }
    bool GetShowCityIconBottom(const MapIconRecord * & rec) const;
    const MapIconRecord * GetShowCityIconBottomPtr() const;
    bool HasSquaredBorderRadius() const { return (m_flags0 & k_Wonder_SquaredBorderRadius_Bit) != 0; }
    bool GetSquaredBorderRadius(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_SquaredBorderRadius_Bit)
        {
            value = m_SquaredBorderRadiusValue;
        }
        return (m_flags0 & k_Wonder_SquaredBorderRadius_Bit) != 0;
    }
    bool HasIntBorderRadius() const { return (m_flags0 & k_Wonder_IntBorderRadius_Bit) != 0; }
    bool GetIntBorderRadius(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_IntBorderRadius_Bit)
        {
            value = m_IntBorderRadiusValue;
        }
        return (m_flags0 & k_Wonder_IntBorderRadius_Bit) != 0;
    }
    bool GetOnePerCiv() const { return (m_flags0 & k_Wonder_OnePerCiv_Bit) != 0; }
    bool HasIsReligionIcon() const { return (m_flags0 & k_Wonder_IsReligionIcon_Bit) != 0; }
    bool GetIsReligionIconIndex(sint32 & index) const
    {
        index = (m_flags0 & k_Wonder_IsReligionIcon_Bit) ? m_IsReligionIconValue : -1;
        return (m_flags0 & k_Wonder_IsReligionIcon_Bit) != 0;
    }
    bool GetIsReligionIcon(const MapIconRecord * & rec) const;
    const MapIconRecord * GetIsReligionIconPtr() const;
    bool GetIsHolyCity() const { return (m_flags0 & k_Wonder_IsHolyCity_Bit) != 0; }
    bool HasReduceReadinessCost() const { return (m_flags0 & k_Wonder_ReduceReadinessCost_Bit) != 0; }
    bool GetReduceReadinessCost(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_ReduceReadinessCost_Bit)
        {
            value = m_ReduceReadinessCostValue;
        }
        return (m_flags0 & k_Wonder_ReduceReadinessCost_Bit) != 0;
    }
    bool GetEmbassiesEverywhere() const { return (m_flags0 & k_Wonder_EmbassiesEverywhere_Bit) != 0; }
    bool HasDecCrimePercent() const { return (m_flags0 & k_Wonder_DecCrimePercent_Bit) != 0; }
    bool GetDecCrimePercent(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_DecCrimePercent_Bit)
        {
            value = m_DecCrimePercentValue;
        }
        return (m_flags0 & k_Wonder_DecCrimePercent_Bit) != 0;
    }
    bool HasIncKnowledgePercent() const { return (m_flags0 & k_Wonder_IncKnowledgePercent_Bit) != 0; }
    bool GetIncKnowledgePercent(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_IncKnowledgePercent_Bit)
        {
            value = m_IncKnowledgePercentValue;
        }
        return (m_flags0 & k_Wonder_IncKnowledgePercent_Bit) != 0;
    }
    bool HasDecEmpireSize() const { return (m_flags0 & k_Wonder_DecEmpireSize_Bit) != 0; }
    bool GetDecEmpireSize(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_DecEmpireSize_Bit)
        {
            value = m_DecEmpireSizeValue;
        }
        return (m_flags0 & k_Wonder_DecEmpireSize_Bit) != 0;
    }
    bool HasIncHappinessEmpire() const { return (m_flags0 & k_Wonder_IncHappinessEmpire_Bit) != 0; }
    bool GetIncHappinessEmpire(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_IncHappinessEmpire_Bit)
        {
            value = m_IncHappinessEmpireValue;
        }
        return (m_flags0 & k_Wonder_IncHappinessEmpire_Bit) != 0;
    }
    bool GetCloseEmbassies() const { return (m_flags0 & k_Wonder_CloseEmbassies_Bit) != 0; }
    bool GetReformCities() const { return (m_flags0 & k_Wonder_ReformCities_Bit) != 0; }
    bool GetFreeSlaves() const { return (m_flags0 & k_Wonder_FreeSlaves_Bit) != 0; }
    bool GetProhibitSlavers() const { return (m_flags0 & k_Wonder_ProhibitSlavers_Bit) != 0; }
    bool HasIncConvertedCitiesFeePercent() const { return (m_flags0 & k_Wonder_IncConvertedCitiesFeePercent_Bit) != 0; }
    bool GetIncConvertedCitiesFeePercent(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_IncConvertedCitiesFeePercent_Bit)
        {
            value = m_IncConvertedCitiesFeePercentValue;
        }
        return (m_flags0 & k_Wonder_IncConvertedCitiesFeePercent_Bit) != 0;
    }
    bool HasGoldPerWaterTradeRoute() const { return (m_flags0 & k_Wonder_GoldPerWaterTradeRoute_Bit) != 0; }
    bool GetGoldPerWaterTradeRoute(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_GoldPerWaterTradeRoute_Bit)
        {
            value = m_GoldPerWaterTradeRouteValue;
        }
        return (m_flags0 & k_Wonder_GoldPerWaterTradeRoute_Bit) != 0;
    }
    bool HasGoldPerTelevision() const { return (m_flags0 & k_Wonder_GoldPerTelevision_Bit) != 0; }
    bool GetGoldPerTelevision(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_GoldPerTelevision_Bit)
        {
            value = m_GoldPerTelevisionValue;
        }
        return (m_flags0 & k_Wonder_GoldPerTelevision_Bit) != 0;
    }
    bool GetGlobalRadar() const { return (m_flags0 & k_Wonder_GlobalRadar_Bit) != 0; }
    bool GetSpiesEverywhere() const { return (m_flags0 & k_Wonder_SpiesEverywhere_Bit) != 0; }
    bool HasGoldPerInternationalTradeRoute() const { return (m_flags0 & k_Wonder_GoldPerInternationalTradeRoute_Bit) != 0; }
    bool GetGoldPerInternationalTradeRoute(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_GoldPerInternationalTradeRoute_Bit)
        {
            value = m_GoldPerInternationalTradeRouteValue;
        }
        return (m_flags0 & k_Wonder_GoldPerInternationalTradeRoute_Bit) != 0;
    }
    bool GetProtectFromBiologicalWarfare() const { return (m_flags0 & k_Wonder_ProtectFromBiologicalWarfare_Bit) != 0; }
    bool HasPollutersToParks() const { return (m_flags0 & k_Wonder_PollutersToParks_Bit) != 0; }
    bool GetPollutersToParks(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_PollutersToParks_Bit)
        {
            value = m_PollutersToParksValue;
        }
        return (m_flags0 & k_Wonder_PollutersToParks_Bit) != 0;
    }
    bool GetEnableParkRangers() const { return (m_flags0 & k_Wonder_EnableParkRangers_Bit) != 0; }
    bool HasReduceWorldPollution() const { return (m_flags0 & k_Wonder_ReduceWorldPollution_Bit) != 0; }
    bool GetReduceWorldPollution(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_ReduceWorldPollution_Bit)
        {
            value = m_ReduceWorldPollutionValue;
        }
        return (m_flags0 & k_Wonder_ReduceWorldPollution_Bit) != 0;
    }
    bool GetAllCitizensContent() const { return (m_flags0 & k_Wonder_AllCitizensContent_Bit) != 0; }
    bool GetEliminateNukes() const { return (m_flags0 & k_Wonder_EliminateNukes_Bit) != 0; }
    bool GetAllBoatsDeepWater() const { return (m_flags0 & k_Wonder_AllBoatsDeepWater_Bit) != 0; }
    bool HasIncreaseBoatMovement() const { return (m_flags0 & k_Wonder_IncreaseBoatMovement_Bit) != 0; }
    bool GetIncreaseBoatMovement(sint32 & value) const
    {
        if (m_flags0 & k_Wonder_IncreaseBoatMovement_Bit)
        {
            value = m_IncreaseBoatMovementValue;
        }
        return (m_flags0 & k_Wonder_IncreaseBoatMovement_Bit) != 0;
    }
    bool GetFreeTradeRoutes() const { return (m_flags0 & k_Wonder_FreeTradeRoutes_Bit) != 0; }
    bool HasDecreaseMaintenance() const { return (m_flags1 & k_Wonder_DecreaseMaintenance_Bit) != 0; }
    bool GetDecreaseMaintenance(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_DecreaseMaintenance_Bit)
        {
            value = m_DecreaseMaintenanceValue;
        }
        return (m_flags1 & k_Wonder_DecreaseMaintenance_Bit) != 0;
    }
    bool HasRandomAdvanceChance() const { return (m_flags1 & k_Wonder_RandomAdvanceChance_Bit) != 0; }
    bool GetRandomAdvanceChance(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_RandomAdvanceChance_Bit)
        {
            value = m_RandomAdvanceChanceValue;
        }
        return (m_flags1 & k_Wonder_RandomAdvanceChance_Bit) != 0;
    }
    bool HasIncreaseHp() const { return (m_flags1 & k_Wonder_IncreaseHp_Bit) != 0; }
    bool GetIncreaseHp(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseHp_Bit)
        {
            value = m_IncreaseHpValue;
        }
        return (m_flags1 & k_Wonder_IncreaseHp_Bit) != 0;
    }
    bool HasMultiplyTradeRoutes() const { return (m_flags1 & k_Wonder_MultiplyTradeRoutes_Bit) != 0; }
    bool GetMultiplyTradeRoutes(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_MultiplyTradeRoutes_Bit)
        {
            value = m_MultiplyTradeRoutesValue;
        }
        return (m_flags1 & k_Wonder_MultiplyTradeRoutes_Bit) != 0;
    }
    bool GetForcefieldEverywhere() const { return (m_flags1 & k_Wonder_ForcefieldEverywhere_Bit) != 0; }
    bool HasIncreaseScientists() const { return (m_flags1 & k_Wonder_IncreaseScientists_Bit) != 0; }
    bool GetIncreaseScientists(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseScientists_Bit)
        {
            value = m_IncreaseScientistsValue;
        }
        return (m_flags1 & k_Wonder_IncreaseScientists_Bit) != 0;
    }
    bool HasOtherCivRandomAdvanceChance() const { return (m_flags1 & k_Wonder_OtherCivRandomAdvanceChance_Bit) != 0; }
    bool GetOtherCivRandomAdvanceChance(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_OtherCivRandomAdvanceChance_Bit)
        {
            value = m_OtherCivRandomAdvanceChanceValue;
        }
        return (m_flags1 & k_Wonder_OtherCivRandomAdvanceChance_Bit) != 0;
    }
    bool HasIncreaseProduction() const { return (m_flags1 & k_Wonder_IncreaseProduction_Bit) != 0; }
    bool GetIncreaseProduction(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseProduction_Bit)
        {
            value = m_IncreaseProductionValue;
        }
        return (m_flags1 & k_Wonder_IncreaseProduction_Bit) != 0;
    }
    bool HasBonusGold() const { return (m_flags1 & k_Wonder_BonusGold_Bit) != 0; }
    bool GetBonusGold(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_BonusGold_Bit)
        {
            value = m_BonusGoldValue;
        }
        return (m_flags1 & k_Wonder_BonusGold_Bit) != 0;
    }
    bool GetCantBuildInSea() const { return (m_flags1 & k_Wonder_CantBuildInSea_Bit) != 0; }
    bool GetCantBuildOnLand() const { return (m_flags1 & k_Wonder_CantBuildOnLand_Bit) != 0; }
    bool GetCoastalBuilding() const { return (m_flags1 & k_Wonder_CoastalBuilding_Bit) != 0; }
    bool GetEnablesPunativeAirstrikes() const { return (m_flags1 & k_Wonder_EnablesPunativeAirstrikes_Bit) != 0; }
    bool HasIncreaseFoodAllCities() const { return (m_flags1 & k_Wonder_IncreaseFoodAllCities_Bit) != 0; }
    bool GetIncreaseFoodAllCities(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseFoodAllCities_Bit)
        {
            value = m_IncreaseFoodAllCitiesValue;
        }
        return (m_flags1 & k_Wonder_IncreaseFoodAllCities_Bit) != 0;
    }
    bool HasTemporaryFullHappiness() const { return (m_flags1 & k_Wonder_TemporaryFullHappiness_Bit) != 0; }
    bool GetTemporaryFullHappiness(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_TemporaryFullHappiness_Bit)
        {
            value = m_TemporaryFullHappinessValue;
        }
        return (m_flags1 & k_Wonder_TemporaryFullHappiness_Bit) != 0;
    }
    bool GetRevoltingCitiesJoinPlayer() const { return (m_flags1 & k_Wonder_RevoltingCitiesJoinPlayer_Bit) != 0; }
    bool GetNoPollutionUnhappiness() const { return (m_flags1 & k_Wonder_NoPollutionUnhappiness_Bit) != 0; }
    bool GetEmbassiesEverywhereEvenAtWar() const { return (m_flags1 & k_Wonder_EmbassiesEverywhereEvenAtWar_Bit) != 0; }
    bool HasIncreaseSpecialists() const { return (m_flags1 & k_Wonder_IncreaseSpecialists_Bit) != 0; }
    bool GetIncreaseSpecialists(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseSpecialists_Bit)
        {
            value = m_IncreaseSpecialistsValue;
        }
        return (m_flags1 & k_Wonder_IncreaseSpecialists_Bit) != 0;
    }
    bool HasIncreaseCathedrals() const { return (m_flags1 & k_Wonder_IncreaseCathedrals_Bit) != 0; }
    bool GetIncreaseCathedrals(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseCathedrals_Bit)
        {
            value = m_IncreaseCathedralsValue;
        }
        return (m_flags1 & k_Wonder_IncreaseCathedrals_Bit) != 0;
    }
    bool HasIncreaseBrokerages() const { return (m_flags1 & k_Wonder_IncreaseBrokerages_Bit) != 0; }
    bool GetIncreaseBrokerages(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseBrokerages_Bit)
        {
            value = m_IncreaseBrokeragesValue;
        }
        return (m_flags1 & k_Wonder_IncreaseBrokerages_Bit) != 0;
    }
    bool HasIncreaseRegard() const { return (m_flags1 & k_Wonder_IncreaseRegard_Bit) != 0; }
    bool GetIncreaseRegard(sint32 & value) const
    {
        if (m_flags1 & k_Wonder_IncreaseRegard_Bit)
        {
            value = m_IncreaseRegardValue;
        }
        return (m_flags1 & k_Wonder_IncreaseRegard_Bit) != 0;
    }
    bool GetPreventConversion() const { return (m_flags1 & k_Wonder_PreventConversion_Bit) != 0; }
    bool GetProtectFromBarbarians() const { return (m_flags1 & k_Wonder_ProtectFromBarbarians_Bit) != 0; }
    bool GetStartGaiaController() const { return (m_flags1 & k_Wonder_StartGaiaController_Bit) != 0; }
    bool GetGLHidden() const { return (m_flags1 & k_Wonder_GLHidden_Bit) != 0; }
    bool HasBuildingFeat() const { return (m_flags1 & k_Wonder_BuildingFeat_Bit) != 0; }
    bool GetBuildingFeat(const BuildingFeat *&ptr) const
    {
        ptr = (m_flags1 & k_Wonder_BuildingFeat_Bit) ? &m_BuildingFeatValue : NULL;
        return (m_flags1 & k_Wonder_BuildingFeat_Bit) != 0;
    }
    const BuildingFeat * GetBuildingFeatPtr() const
    {
        return (m_flags1 & k_Wonder_BuildingFeat_Bit) ? &m_BuildingFeatValue : NULL;
    }
    bool HasBuildingGold() const { return (m_flags1 & k_Wonder_BuildingGold_Bit) != 0; }
    bool GetBuildingGold(const BuildingGold *&ptr) const
    {
        ptr = (m_flags1 & k_Wonder_BuildingGold_Bit) ? &m_BuildingGoldValue : NULL;
        return (m_flags1 & k_Wonder_BuildingGold_Bit) != 0;
    }
    const BuildingGold * GetBuildingGoldPtr() const
    {
        return (m_flags1 & k_Wonder_BuildingGold_Bit) ? &m_BuildingGoldValue : NULL;
    }
    bool HasBuildingEverywhere() const { return (m_flags1 & k_Wonder_BuildingEverywhere_Bit) != 0; }
    bool GetBuildingEverywhereIndex(sint32 & index) const
    {
        index = (m_flags1 & k_Wonder_BuildingEverywhere_Bit) ? m_BuildingEverywhereValue : -1;
        return (m_flags1 & k_Wonder_BuildingEverywhere_Bit) != 0;
    }
    bool GetBuildingEverywhere(const BuildingRecord * & rec) const;
    const BuildingRecord * GetBuildingEverywherePtr() const;
    bool HasActualBuildingEverywhere() const { return (m_flags1 & k_Wonder_ActualBuildingEverywhere_Bit) != 0; }
    bool GetActualBuildingEverywhereIndex(sint32 & index) const
    {
        index = (m_flags1 & k_Wonder_ActualBuildingEverywhere_Bit) ? m_ActualBuildingEverywhereValue : -1;
        return (m_flags1 & k_Wonder_ActualBuildingEverywhere_Bit) != 0;
    }
    bool GetActualBuildingEverywhere(const BuildingRecord * & rec) const;
    const BuildingRecord * GetActualBuildingEverywherePtr() const;
    bool HasBuildingEffectEverywhere() const { return (m_flags1 & k_Wonder_BuildingEffectEverywhere_Bit) != 0; }
    bool GetBuildingEffectEverywhereIndex(sint32 & index) const
    {
        index = (m_flags1 & k_Wonder_BuildingEffectEverywhere_Bit) ? m_BuildingEffectEverywhereValue : -1;
        return (m_flags1 & k_Wonder_BuildingEffectEverywhere_Bit) != 0;
    }
    bool GetBuildingEffectEverywhere(const BuildingRecord * & rec) const;
    const BuildingRecord * GetBuildingEffectEverywherePtr() const;
    bool HasConflictsWithBuilding() const { return (m_flags1 & k_Wonder_ConflictsWithBuilding_Bit) != 0; }
    bool GetConflictsWithBuildingIndex(sint32 & index) const
    {
        index = (m_flags1 & k_Wonder_ConflictsWithBuilding_Bit) ? m_ConflictsWithBuildingValue : -1;
        return (m_flags1 & k_Wonder_ConflictsWithBuilding_Bit) != 0;
    }
    bool GetConflictsWithBuilding(const BuildingRecord * & rec) const;
    const BuildingRecord * GetConflictsWithBuildingPtr() const;
    sint32 GetBuildingAnywhereIndex(sint32 index) const;
    const BuildingRecord * GetBuildingAnywhere(sint32 index) const;
    sint32 GetNumBuildingAnywhere() const { return m_numBuildingAnywhere;}
    bool HasGoldPerBuildingAnywhere() const { return (m_flags2 & k_Wonder_GoldPerBuildingAnywhere_Bit) != 0; }
    bool GetGoldPerBuildingAnywhere(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_GoldPerBuildingAnywhere_Bit)
        {
            value = m_GoldPerBuildingAnywhereValue;
        }
        return (m_flags2 & k_Wonder_GoldPerBuildingAnywhere_Bit) != 0;
    }
    bool HasPollutionPercent() const { return (m_flags2 & k_Wonder_PollutionPercent_Bit) != 0; }
    bool GetPollutionPercent(double & value) const
    {
        if (m_flags2 & k_Wonder_PollutionPercent_Bit)
        {
            value = m_PollutionPercentValue;
        }
        return (m_flags2 & k_Wonder_PollutionPercent_Bit) != 0;
    }
    bool HasPollutionAmount() const { return (m_flags2 & k_Wonder_PollutionAmount_Bit) != 0; }
    bool GetPollutionAmount(double & value) const
    {
        if (m_flags2 & k_Wonder_PollutionAmount_Bit)
        {
            value = m_PollutionAmountValue;
        }
        return (m_flags2 & k_Wonder_PollutionAmount_Bit) != 0;
    }
    sint32 GetExcludedByBuildingIndex(sint32 index) const;
    const BuildingRecord * GetExcludedByBuilding(sint32 index) const;
    sint32 GetNumExcludedByBuilding() const { return m_numExcludedByBuilding;}
    sint32 GetExcludedByWonderIndex(sint32 index) const;
    const WonderRecord * GetExcludedByWonder(sint32 index) const;
    sint32 GetNumExcludedByWonder() const { return m_numExcludedByWonder;}
    bool HasEnergyHunger() const { return (m_flags2 & k_Wonder_EnergyHunger_Bit) != 0; }
    bool GetEnergyHunger(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_EnergyHunger_Bit)
        {
            value = m_EnergyHungerValue;
        }
        return (m_flags2 & k_Wonder_EnergyHunger_Bit) != 0;
    }
    bool HasProducesEnergy() const { return (m_flags2 & k_Wonder_ProducesEnergy_Bit) != 0; }
    bool GetProducesEnergy(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_ProducesEnergy_Bit)
        {
            value = m_ProducesEnergyValue;
        }
        return (m_flags2 & k_Wonder_ProducesEnergy_Bit) != 0;
    }
    bool HasEnergyHungerPerPop() const { return (m_flags2 & k_Wonder_EnergyHungerPerPop_Bit) != 0; }
    bool GetEnergyHungerPerPop(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_EnergyHungerPerPop_Bit)
        {
            value = m_EnergyHungerPerPopValue;
        }
        return (m_flags2 & k_Wonder_EnergyHungerPerPop_Bit) != 0;
    }
    bool HasProducesEnergyPerPop() const { return (m_flags2 & k_Wonder_ProducesEnergyPerPop_Bit) != 0; }
    bool GetProducesEnergyPerPop(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_ProducesEnergyPerPop_Bit)
        {
            value = m_ProducesEnergyPerPopValue;
        }
        return (m_flags2 & k_Wonder_ProducesEnergyPerPop_Bit) != 0;
    }
    bool HasTooManyCitiesThresholdModifier() const { return (m_flags2 & k_Wonder_TooManyCitiesThresholdModifier_Bit) != 0; }
    bool GetTooManyCitiesThresholdModifier(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_TooManyCitiesThresholdModifier_Bit)
        {
            value = m_TooManyCitiesThresholdModifierValue;
        }
        return (m_flags2 & k_Wonder_TooManyCitiesThresholdModifier_Bit) != 0;
    }
    bool HasTooManyCitiesCoefficientModifier() const { return (m_flags2 & k_Wonder_TooManyCitiesCoefficientModifier_Bit) != 0; }
    bool GetTooManyCitiesCoefficientModifier(double & value) const
    {
        if (m_flags2 & k_Wonder_TooManyCitiesCoefficientModifier_Bit)
        {
            value = m_TooManyCitiesCoefficientModifierValue;
        }
        return (m_flags2 & k_Wonder_TooManyCitiesCoefficientModifier_Bit) != 0;
    }
    bool HasRiotLevelModifier() const { return (m_flags2 & k_Wonder_RiotLevelModifier_Bit) != 0; }
    bool GetRiotLevelModifier(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_RiotLevelModifier_Bit)
        {
            value = m_RiotLevelModifierValue;
        }
        return (m_flags2 & k_Wonder_RiotLevelModifier_Bit) != 0;
    }
    bool HasOtherPlayerRiotLevelModifier() const { return (m_flags2 & k_Wonder_OtherPlayerRiotLevelModifier_Bit) != 0; }
    bool GetOtherPlayerRiotLevelModifier(sint32 & value) const
    {
        if (m_flags2 & k_Wonder_OtherPlayerRiotLevelModifier_Bit)
        {
            value = m_OtherPlayerRiotLevelModifierValue;
        }
        return (m_flags2 & k_Wonder_OtherPlayerRiotLevelModifier_Bit) != 0;
    }
    bool GetHasGovernmentsModified() const { return m_hasGovernmentsModified; }
    sint32 GenericGetNumGovernmentsModified() const { return m_numGovernmentsModified; }
    sint32 GenericGetGovernmentsModifiedIndex(sint32 index) const { return GetGovernmentsModifiedIndex(index); }

}; /* WonderRecord */

struct WonderRecordAccessorInfo
{
    WonderRecord::IntAccessor        m_intAccessor;
    WonderRecord::BoolAccessor       m_boolAccessor;
    WonderRecord::FloatAccessor      m_floatAccessor;
    WonderRecord::BitIntAccessor     m_bitIntAccessor;
    WonderRecord::BitFloatAccessor   m_bitFloatAccessor;
    WonderRecord::IntArrayAccessor   m_intArrayAccessor;
    WonderRecord::FloatArrayAccessor m_floatArrayAccessor;
};

extern WonderRecordAccessorInfo      g_WonderRecord_Accessors[];
extern CTPDatabase<WonderRecord> *   g_theWonderDB;

extern const char * g_Wonder_Tokens[];

#endif
